volumes:
  shared_data:

services:
  redis:
    container_name: redis
    image: redis/redis-stack-server
    ports:
      - '6379:6379'
  celery-worker:
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    container_name: celery-worker-1
    working_dir: /s3fileuploader/src
    command: celery -A celery_app.celery worker --loglevel DEBUG
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis
      - APP_HOST=0.0.0.0
      - APP_PORT=9000
      - AWS_ENDPOINT=http://moto:3000
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - AWS_SESSION_TOKEN=testing
      - AWS_REGION=us-east-1
      - STORAGE_PATH=${STORAGE_PATH:-/shared_data/}
    volumes:
      - /tmp:/shared_data
    depends_on:
      - redis
  celery-worker-2:
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    container_name: celery-worker-2
    working_dir: /s3fileuploader/src
    command: celery -A celery_app.celery worker --loglevel DEBUG
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis
      - APP_HOST=0.0.0.0
      - APP_PORT=9000
      - AWS_ENDPOINT=http://moto:3000
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - AWS_SESSION_TOKEN=testing
      - AWS_REGION=us-east-1
      - STORAGE_PATH=${STORAGE_PATH:-/shared_data/}
    volumes:
      - /tmp:/shared_data
    depends_on:
      - redis
  moto:
    # S3 mock
    container_name: moto
    image: motoserver/moto:latest
    ports:
      - "3000:3000"
    environment:
      - MOTO_PORT=3000 # set moto listener port with env var
  s3-file-uploader:
    container_name: s3-file-uploader
    command: python /s3fileuploader/src/main.py
    environment:
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis
      - APP_HOST=0.0.0.0
      - APP_PORT=9000
      - AWS_ENDPOINT=http://moto:3000
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - AWS_SESSION_TOKEN=testing
      - AWS_REGION=us-east-1
      - STORAGE_PATH=${STORAGE_PATH:-/shared_data/}
    volumes:
      - /tmp:/shared_data
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    ports:
      - '9000:9000'
    depends_on:
      - redis
      - moto
      - celery-worker
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    depends_on:
      - s3-file-uploader