name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.8"
      - name: Install dependencies
        run: make install-requirements
      - name: Lint
        run: make lint
      - name: Test with pytest
        run: make test
      - name: Set up docker composer
        run: make devstack-up
      - name: Run feature tests
        run: make feature-test
      - name: Spool devstack logs
        if: ${{ always() }}
        run: make devstack-logs
      - name: Tear Down docker composer
        run: make devstack-down